### ISSUE TITLE
[Vue warn]: Invalid prop: type check failed for prop "placeholder".

### ISSUE THREAD

**Issue by CAT6e** [soc221b/vue-next-select#111]
Hi,

I used vue-next-select by writing this "Single select (object)" example 
[https://iendeavor.github.io/vue-next-select/#single-select-object-header](https://iendeavor.github.io/vue-next-select/#single-select-object-header)

However, "options" variable has an 'id' property that contains numbers.
`
<template>
   <vue-select
                v-model="model"
                :options="options"
                :visible-options="visibleOptions"
                label-by="id"
                track-by="id"
                searchable
                clear-on-select
                close-on-select
                @search:input="handleSearchInput" />
</template>

...
// Example options variable
const options = [
      { id: 1, language: 'JavaScript' },
      { id: 2, language: 'Python' },
      { id: 3, language: 'PHP' }
    ]
`

The following warning will be thrown if I select an item from the dropdown.
`[Vue warn]: Invalid prop: type check failed for prop "placeholder". Expected String with value "2", got Number with value 2. 
  at <VueInput key=0 ref="input" modelValue=""  ... > 
`

I tried passing `type="number"` to the <vue-select> element, but this warning's still existed. 

It would be great if this warning disappears.

Thank you.

**Comment by iendeavor** [comment]
Reproduce link:
https://codesandbox.io/s/vue-next-select-111-qm7u4?file=/src/components/HelloWorld.vue

Reproduce steps:
1. open console
2. select an item
3. close dropdown

This bug is caused by the type of label which is number, typically the label would not be a number, but I will fix it soon.

Thanks for the feedback :smile:.
